[gcp_service_account]
type = "service_account"
project_id = "my-project-shimakiti-426301"
private_key_id = "c7666399b22b37f0acb8dcf28c53e84ffc73cdcc"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDxLJupjO/LgK2d
CQ5VK13zg/I7ejax5CKd2Lrkn5JagHQo/6N791zOrAONF06saT2cHjOqsWFXjnPz
IgXIUaFOzLPJsjkvL0jfzUqJ0hi91r8II0VkfHiz14Oqg5imGDAOlKmXf/zuq0UH
Bv5+uEMrkD6dsl8N3jD7Kwq6rsf2N2DsqqDgTPW6vPlbNdMY8kF0VprftJrrRhY+
wBaVVeCX8eNskbTaDs6bAcqiu9l4d7g/aYFPqSOMdBOrJU+PfoYq5vcudZNNEj58
yl2h4tV1ZDSPxA52Yst02WLJ0HzavNJE6KTZmRGEpFOLhSqwsVxxeLIl3JMouAcT
dWki+Yk3AgMBAAECggEAC9zFVUwc2VYdc/1nipHk/57MUdebjBlsCHaKDse4g6IQ
1JlqWaUbmADG9fAhCwLsKFsl8G3kG1Hi6yEPxsAZHo6cAz40aNk7DOMEmQ3P8Lp4
z/YoKh6jMzlU/RSW9Ah5iKYQR2bgsn6TGRrjdqkqiKCCK/CDk2OL5jbCQtdo93e+
Z6hgkn9TxPEba9h30ALl446mCHINvDN7lv/DWV7MLOIoKClAlGgNeeMxue4GLD0W
QzxGBnIjtCFJXqGDq9YEN52fttFZQrYHb7uMXRouqUSaNCI9UQd1jdB41RxBZr56
YuhouPbML3cHJgIX45wlBCnR4as0A63c3W5SWJCiVQKBgQD5FeVfBtOwkK/bLGkt
PHbgTngIcHYhjIafXBIhU89yx2jg6R8mLODnL6779a1f8+j5kMSjsmX0LMtPJekK
vk2YATlik+7YG358NofDZYuF8tfGDh+R8w+Lyt7BEE3flcfGGGaE9IFeRbu7yOIr
ycv5abfBtflOPbvHM0oRJBgLUwKBgQD33n3DjAzigds3H5mSAjpYVhKLCpOOCbcF
6qIEkqNA7gMcI8wUo9ZbNrJB3DXRSs0MFoSuYjP3AY0XR3+Cxi1QCJLo8umE/Kmg
YeX+r5xh2/Nv/yAkax7yNf0fKCum6yV7P05+SrRq1iQRJV9NElWXvRNASqJzWKtw
fr/zQ7JyDQKBgFukYq+Do37ivNC2lju+cz4zoJX6SnwtZ5paFZGNdFWWaE/XdU5m
VJi6QncQ/KjA5IZtbOuNR1V+5Y5JNGRvf7zdNm++XbHE69Rne6u4QI0Xu6typsrb
0mxsR2hgx0XrpYSMlat1CePVZCzCy/OwWwt4idMLUJ4ouF2h0S5dSTthAoGALiFt
XIhjGYC7cK3j4eWiQDB8sP3d6lBqjKJXVuyHj5z8XS9YWvsG+ODcGh/GsFXwhXBn
byD9tNnIDW4UEB2b70o5NTuINGTlmOC/cj/ypc/OpahgrgZ1svRTUIokXaNjzWVB
0YVLwJpsCfjfnLNt1JiuzYdWZos5FO2yAa82tb0CgYBZ/pIjYLxnhu/9vhUjVym5
vU/YI/uL7GfisVWkgtpHzlc+m5cKLW+HxmWKZV12psP0tnEYJ7iTNPIHNYu5Q4Vp
WmzH5Qni4FHC0mtgGL/BCVoO5II3QGF4xXUWt7CFZzYY1FxUlAdmdQdMruOqExAM
hT2W9Vw+jLTyKtoEOJGdsg==
-----END PRIVATE KEY-----"""
client_email = "manga-check@my-project-shimakiti-426301.iam.gserviceaccount.com"
client_id = "105362566288049264278"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/manga-check%40my-project-shimakiti-426301.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

[rakuten]
applicationId = "1076430395186832332"
affiliateId = "4007a5ec.ac9ca83d.4007a5ed.adc3dffb"
